version: '3.8'

services:
  web:
    build: .
    command: uvicorn ShortLink.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pegasuss
      - POSTGRES_DB=ubuntu
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - web
volumes:
  static_volume: